import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import "bootstrap/dist/css/bootstrap.min.css";
import ContextApi from "@/context/ContextApi";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextApi>
          <Navbar />
          <Sidebar />
          {children}
        </ContextApi>
      </body>
    </html>
  );
}
